# PARENT 아이템 : A에서 B가 될 때, A
# ROOT 아이템 : PARENT가 없는 아이템
# 아이템 정보 ITEM_INFO
# 아이템 관계 ITEM_TREE
# LEFT 조인 해서 PARENT_ID가 NULL인거
SELECT I.ITEM_ID, ITEM_NAME
FROM ITEM_INFO I
    JOIN ITEM_TREE T
    ON I.ITEM_ID = T.ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID