-- 코드를 입력하세요
# 주문 정보 FIRST_HALF : SHIPMENT_ID, FLAVOR*, TOTAL_ORDER
# 성분 정보 ICECREAM_INFO : FLAVOR*, INGREDIENT_TYPE
# 각 아이스크림의 성분 타입과 성분 타입에 따른 총 주문량
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
    JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE;